[package]
name = "orbit"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ariadne.workspace = true
orbit-common.workspace = true
orbit-compiler.workspace = true
orbit-loader.workspace = true
orbit-stdlib.workspace = true
orbit-vm.workspace = true
