[package]
name = "orbit-compiler"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
orbit-common.workspace = true
orbit-resolver.workspace = true
thiserror.workspace = true

[dev-dependencies]
orbit-parser.workspace = true
