[package]
name = "orbit-loader"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
orbit-common.workspace = true
orbit-compiler.workspace = true
orbit-parser.workspace = true
orbit-resolver.workspace = true
orbit-vm.workspace = true
